/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/custom-component': RouteRecordInfo<
      '/custom-component',
      '/custom-component',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/emoji': RouteRecordInfo<
      '/emoji',
      '/emoji',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/etc': RouteRecordInfo<
      '/etc',
      '/etc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/img': RouteRecordInfo<
      '/img',
      '/img',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/link': RouteRecordInfo<
      '/link',
      '/link',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/router-link': RouteRecordInfo<
      '/router-link',
      '/router-link',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/table': RouteRecordInfo<
      '/table',
      '/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tailwind': RouteRecordInfo<
      '/tailwind',
      '/tailwind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/text-style': RouteRecordInfo<
      '/text-style',
      '/text-style',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/custom-component.vue': {
      routes:
        | '/custom-component'
      views:
        | never
    }
    'src/pages/emoji.vue': {
      routes:
        | '/emoji'
      views:
        | never
    }
    'src/pages/etc.vue': {
      routes:
        | '/etc'
      views:
        | never
    }
    'src/pages/img.vue': {
      routes:
        | '/img'
      views:
        | never
    }
    'src/pages/link.vue': {
      routes:
        | '/link'
      views:
        | never
    }
    'src/pages/router-link.vue': {
      routes:
        | '/router-link'
      views:
        | never
    }
    'src/pages/table.vue': {
      routes:
        | '/table'
      views:
        | never
    }
    'src/pages/tailwind.vue': {
      routes:
        | '/tailwind'
      views:
        | never
    }
    'src/pages/text-style.vue': {
      routes:
        | '/text-style'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
