/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/custom-component': RouteRecordInfo<'/custom-component', '/custom-component', Record<never, never>, Record<never, never>>,
    '/emoji': RouteRecordInfo<'/emoji', '/emoji', Record<never, never>, Record<never, never>>,
    '/etc': RouteRecordInfo<'/etc', '/etc', Record<never, never>, Record<never, never>>,
    '/img': RouteRecordInfo<'/img', '/img', Record<never, never>, Record<never, never>>,
    '/link': RouteRecordInfo<'/link', '/link', Record<never, never>, Record<never, never>>,
    '/router-link': RouteRecordInfo<'/router-link', '/router-link', Record<never, never>, Record<never, never>>,
    '/table': RouteRecordInfo<'/table', '/table', Record<never, never>, Record<never, never>>,
    '/tailwind': RouteRecordInfo<'/tailwind', '/tailwind', Record<never, never>, Record<never, never>>,
    '/text-style': RouteRecordInfo<'/text-style', '/text-style', Record<never, never>, Record<never, never>>,
  }
}
